spring.application.name=backend
spring.datasource.url=jdbc:postgresql://db:5432/plately
spring.datasource.username=plately
spring.datasource.password=plately
spring.datasource.driver-class-name=org.postgresql.Driver