spring.application.name=backend

spring.datasource.url=jdbc:postgresql://db:5432/plately
spring.datasource.username=plately
spring.datasource.password=plately
spring.datasource.driver-class-name=org.postgresql.Driver

jwt.secret=fa492ce31ea5f44361b8f1d8ad9fae511a17a6fd7f0f9ecd472d202eec0faf69
jwt.expiration=86400000

spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
logging.level.org.springframework.security=DEBUG